[package]
name = "aleo-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "./src/main.rs"

[dependencies]
stratum-pool = { path = "../stratum-pool" }
snarkvm = { workspace = true }
snarkos-node = { git = "https://github.com/AleoHQ/snarkOS.git", branch = "testnet3" }

