[package]
name = "aleo-worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "worker"
path = "./src/main.rs"

[dependencies]
stratum-worker = { path = "../stratum-worker" }
clap = { version = "4.0.9", features = ["derive"] }
anyhow = "*"
simple-log = "1.6.0"
snarkvm = { workspace = true }
